# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when toolkit is run from outside a project.

#################################################################################################
# define all the items that should appear in this environment
# By default make the non-project side of the desktop engine available

engines:
  tk-desktop:
    apps:
    show_recents: true
    groups: []
    default_group: Studio
    collapse_rules: []
    hook_launch_python: default
    debug_logging: false
    location: {name: tk-desktop, type: app_store, version: v1.0.0}

frameworks:
  tk-framework-qtwidgets_v1.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v1.0.1}
  tk-framework-shotgunutils_v2.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v2.0.5}
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.0.2}
  tk-framework-adminui_v0.x.x:
    location: {name: tk-framework-adminui, type: app_store, version: v0.0.6}
